# ============================================================
# Application : The Internet (Heroku)
# Environment : STAGE
# ============================================================
env      = stage
url      = https://the-internet.herokuapp.com
username = tomsmith
password = SuperSecretPassword!
browser  = chrome
