# ============================================================
# Application : The Internet (Heroku)
# Environment : QA  (default)
# ============================================================
env      = qa
url      = https://the-internet.herokuapp.com
username = tomsmith
password = SuperSecretPassword!
browser  = chrome
