# ============================================================
# Application : The Internet (Heroku)
# Environment : DEV
# ============================================================
env      = dev
url      = https://the-internet.herokuapp.com
username = tomsmith
password = SuperSecretPassword!
browser  = chrome
