# ============================================================
# Application : JSONPlaceholder API
# Environment : PROD
# ============================================================
env     = prod
baseUri = https://jsonplaceholder.typicode.com
