# ============================================================
# Application : JSONPlaceholder API
# Environment : QA  (default)
# ============================================================
env     = qa
baseUri = https://jsonplaceholder.typicode.com
