# ============================================================
# Application : JSONPlaceholder API
# Environment : STAGE
# ============================================================
env     = stage
baseUri = https://jsonplaceholder.typicode.com
