# ============================================================
# Application : JSONPlaceholder API
# Environment : DEV
# ============================================================
env     = dev
baseUri = https://jsonplaceholder.typicode.com
