# ============================================================
# Environment : PROD
# ============================================================
env      = prod
url      = https://prod.practicetestautomation.com/practice-test-login/
username = prod_student
password = ProdPassword123
browser  = chrome
