# ============================================================
# Environment : DEV
# ============================================================
env      = dev
url      = https://dev.practicetestautomation.com/practice-test-login/
username = dev_student
password = DevPassword123
browser  = chrome
