# ============================================================
# Environment : STAGE
# ============================================================
env      = stage
url      = https://stage.practicetestautomation.com/practice-test-login/
username = stage_student
password = StagePassword123
browser  = chrome
